-- GymTracker initial schema.
--
-- Three axioms, carried from docs/BACKEND_GUIDE.md:
--   1. Exercise and program ids stay TEXT ('ex_bench_press', 'prog_ppl'). Existing
--      installs already reference those strings; numeric ids would orphan history.
--   2. User-data ids are UUIDs generated by the client, so records created offline
--      already carry their permanent id and need no remapping on sync.
--   3. Every syncable table carries updated_at and a nullable deleted_at. Deletes are
--      soft: a hard delete is invisible to a device that was offline when it happened,
--      so that device would happily re-upload the row it still has.
--
-- Weights are kg, lengths are cm. Conversion to lb/inches is a presentation concern.

-- ---------------------------------------------------------------- users

CREATE TABLE users (
    id              UUID PRIMARY KEY,
    name            TEXT        NOT NULL,
    email           TEXT        NOT NULL,
    password_hash   TEXT        NOT NULL,
    photo_seed      INTEGER     NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Onboarding profile. NULL as a unit: the app treats profile == null as
    -- "onboarding incomplete" and redirects to /onboarding.
    gender           TEXT,
    age              INTEGER,
    height_cm        NUMERIC(5,1),
    weight_kg        NUMERIC(5,1),
    goal             TEXT,
    experience       TEXT,
    weekly_frequency INTEGER
);

-- Case-insensitive uniqueness without the citext extension: citext reports as
-- Types#OTHER over JDBC, which Hibernate's ddl-auto:validate rejects against a String
-- field. The app lowercases on register and on every lookup; this index enforces it.
CREATE UNIQUE INDEX idx_users_email_lower ON users (lower(email));

-- Refresh tokens are hashed at rest and revocable; logout sets revoked_at.
CREATE TABLE refresh_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT        NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);

-- ---------------------------------------------------------------- settings

CREATE TABLE user_settings (
    user_id                   UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    units                     TEXT        NOT NULL DEFAULT 'metric',
    dark_mode                 BOOLEAN     NOT NULL DEFAULT TRUE,
    notifications_enabled     BOOLEAN     NOT NULL DEFAULT TRUE,
    workout_reminders_enabled BOOLEAN     NOT NULL DEFAULT TRUE,
    reminder_time             TEXT        NOT NULL DEFAULT '18:00',
    rest_timer_sound          BOOLEAN     NOT NULL DEFAULT TRUE,
    language                  TEXT        NOT NULL DEFAULT 'English',
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- favorites

CREATE TABLE favorites (
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exercise_id TEXT        NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at  TIMESTAMPTZ,
    PRIMARY KEY (user_id, exercise_id)
);

CREATE INDEX idx_favorites_user_updated ON favorites(user_id, updated_at);

-- ---------------------------------------------------------------- workouts

-- program_id and exercise_id are unconstrained TEXT on purpose: the exercise and
-- program catalog lives in the app's bundled seed data, not on the server. A workout
-- log must never fail to sync because the server's catalog lags the client's.
CREATE TABLE workout_logs (
    id              UUID PRIMARY KEY,
    user_id         UUID          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    program_id      TEXT,
    day_name        TEXT          NOT NULL,
    started_at      TIMESTAMPTZ   NOT NULL,
    ended_at        TIMESTAMPTZ   NOT NULL,
    duration_sec    INTEGER       NOT NULL,
    total_volume_kg NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_sets      INTEGER       NOT NULL DEFAULT 0,
    calories_est    INTEGER       NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX idx_workout_logs_user_updated ON workout_logs(user_id, updated_at);

-- sort_order is required: the Dart models rely on list order and JSON arrays have no
-- ordering guarantee once rows round-trip through the database.
CREATE TABLE exercise_logs (
    id              BIGSERIAL PRIMARY KEY,
    workout_log_id  UUID    NOT NULL REFERENCES workout_logs(id) ON DELETE CASCADE,
    exercise_id     TEXT    NOT NULL,
    sort_order      INTEGER NOT NULL,
    UNIQUE (workout_log_id, sort_order)
);

CREATE INDEX idx_exercise_logs_workout ON exercise_logs(workout_log_id);

CREATE TABLE set_logs (
    id              BIGSERIAL PRIMARY KEY,
    exercise_log_id BIGINT       NOT NULL REFERENCES exercise_logs(id) ON DELETE CASCADE,
    weight_kg       NUMERIC(6,2) NOT NULL DEFAULT 0,
    reps            INTEGER      NOT NULL DEFAULT 0,
    completed       BOOLEAN      NOT NULL DEFAULT FALSE,
    skipped         BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order      INTEGER      NOT NULL,
    UNIQUE (exercise_log_id, sort_order)
);

CREATE INDEX idx_set_logs_exercise ON set_logs(exercise_log_id);

-- ---------------------------------------------------------------- measurements

CREATE TABLE measurements (
    id            UUID PRIMARY KEY,
    user_id       UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date          TIMESTAMPTZ NOT NULL,
    weight_kg     NUMERIC(6,2),
    body_fat_pct  NUMERIC(5,2),
    chest_cm      NUMERIC(5,1),
    waist_cm      NUMERIC(5,1),
    arms_cm       NUMERIC(5,1),
    legs_cm       NUMERIC(5,1),
    shoulders_cm  NUMERIC(5,1),
    neck_cm       NUMERIC(5,1),
    hips_cm       NUMERIC(5,1),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);

CREATE INDEX idx_measurements_user_updated ON measurements(user_id, updated_at);
