package com.patriche.gymtracker.user;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;

/**
 * The id is supplied by the caller, never generated by the database - clients mint
 * their own UUIDs so records created offline already carry their permanent id.
 */
@Entity
@Table(name = "users")
public class User {

    @Id
    private UUID id;

    @Column(nullable = false)
    private String name;

    /** Stored lowercased; a unique index on lower(email) enforces that at the database. */
    @Column(nullable = false, unique = true)
    private String email;

    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    @Column(name = "photo_seed", nullable = false)
    private int photoSeed;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /** Onboarding profile - null as a unit means onboarding is incomplete. */
    @Embedded
    private UserProfile profile;

    protected User() {}

    public User(UUID id, String name, String email, String passwordHash, int photoSeed, Instant now) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.passwordHash = passwordHash;
        this.photoSeed = photoSeed;
        this.createdAt = now;
        this.updatedAt = now;
    }

    public UUID getId() { return id; }
    public String getName() { return name; }
    public String getEmail() { return email; }
    public String getPasswordHash() { return passwordHash; }
    public int getPhotoSeed() { return photoSeed; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
    public UserProfile getProfile() { return profile; }

    public void setName(String name) { this.name = name; }
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
    public void setPhotoSeed(int photoSeed) { this.photoSeed = photoSeed; }
    public void setProfile(UserProfile profile) { this.profile = profile; }
    public void touch(Instant now) { this.updatedAt = now; }
}
